# Generated by Django 2.1.7 on 2020-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Roll', models.CharField(max_length=40)),
                ('sub_1', models.IntegerField()),
                ('sub_2', models.IntegerField()),
                ('sub_3', models.IntegerField()),
                ('percent', models.IntegerField(default=0)),
            ],
        ),
    ]
